version: '3.8'

services:
  # MongoDB
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  # Backend API
  api:
    container_name: backend
    build: ./
    command: yarn start
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/rba-using-jwt
      JWT_SECRET: secret
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb